/**
* Name: Deplacementdevelos
* Based on the internal empty template. 
* Author: nathancoisne
* Tags: 
*/


model Deplacementdevelos

/* 
 * This model adds agent name to the .shp of travels generated by 'travel agents'
 * 
 */

global {
		
	file bound <- shape_file("../includes/Marseille/boundary_Marseille.shp");
	      
    geometry shape <- envelope(bound);

    graph the_graph;
        
    

    init{    	
		loop i from: 0 to: 2236{
			
			create type_of_agent{
				type_agent <- "student[" + i + "]";
			
				create position_agent from: shape_file("../results/Marseille/aller_student/aller_student[" + i + "].shp") with: [date_of_presence::(read("time"))]{
					type_agent <- "student[" + i + "]";
					
					myself.list_of_positions << self;
				}
			}
		}
		
		save position_agent to: "../results/Marseille/aller_student.shp" type: shp
				attributes: ["time"::date_of_presence, "agent"::type_agent] crs: "2154";
				
    }          
}


species type_of_agent{
	list<position_agent> list_of_positions;
	string type_agent;
}

species position_agent {
	date date_of_presence;
	string type_agent;
}


experiment bike_traffic type: gui {

}
